app/src/routes.py
from flask import Blueprint, render_template, current_app, session, request, redirect, url_for, flash
from .models import db, User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from app.src.logging_config import logger, savedLevel
# from sqlalchemy import func, select
# from datetime import datetime, date, timedelta
# from dateutil.relativedelta import relativedelta
import logging
# import requests
# import os

bp = Blueprint('main', __name__)

@bp.route('/')
def home():
    logger.debug(f"Home function entered in routes.py Session ID: {session.get('session_id')}")
    logger.info("Home page requested")

    # get README.md content
    # readme_file = get_file_content(os.getcwd() + '/README.md')

    logger.debug("Home function exited in routes.py")
    return render_template('home.html')#, content=readme_file)


security_questions = ["What is your hometown?", "What was the name of your first pet?", "What is your mother's maiden name?"]


# ------------------------------
@bp.route('/register', methods=['GET', 'POST'])
def register():
    logger.debug(f"Register function entered in routes.py method: {request.method}")
    logger.info("Registration attempt initiated")
    logger.debug(f"Session ID: {session.get('session_id')}")
    if request.method == 'POST':
        email = request.form['email']
        nickname = request.form['nickname']
        password = request.form['password']
        answer1 = request.form['answer1']
        answer2 = request.form['answer2']
        answer3 = request.form['answer3']
        # role = request.form.get('role') or 'user'

        # Check for existing email and nickname
        if User.query.filter_by(email=email).first():
            logger.warning("Registration failed: Email already taken")
            logger.debug("Register function exited with failure in routes.py")
            flash("Email already taken!", "warning")
            return redirect(url_for('main.register'))

        if User.query.filter_by(nickname=nickname).first():
            logger.warning("Registration failed: Nickname already taken")
            logger.debug("Register function exited with failure in routes.py")
            flash("Nickname already taken!", "warning")
            return redirect(url_for('main.register'))

        # Hash password, add user data to db
        hashed_password = generate_password_hash(password)
        user = User(email=email, nickname=nickname, password=hashed_password, security_answers=[answer1, answer2, answer3])#, role=role)
        db.session.add(user)
        db.session.commit()
        logger.debug(f"User {nickname} registered in database")
        logger.info(f"New user registered: {nickname}")

        flash("Registration successful! Please login.", "success")
        logger.debug("Register function exited with success in routes.py")
        return redirect(url_for('main.login'))
    
    logger.debug("Register function exited from GET request in routes.py")
    return render_template('register.html', security_questions=security_questions)


# ------------------------------
@bp.route('/login', methods=['GET', 'POST'])
def login():
    logger.debug(f"Login function entered in routes.py method: {request.method}")
    if request.method == 'POST':
        logger.info("Login attempt")
        logger.debug(f"Session ID: {session.get('session_id')}")
        identity = request.form['identity']
        password = request.form['password']

        # Search for user using nickname / email
        user = User.query.filter((User.email == identity) | (User.nickname == identity)).first()
        logger.debug(f"User found: {user.nickname if user else 'None'}")

        # Make sure the password matches
        if user and check_password_hash(user.password, password):
            login_user(user)
            logger.info(f"Authentication success for user: {user.nickname}")
            flash("Welcome back!", "success")
            logger.debug("Login function exited with success as user in routes.py")
            return redirect(url_for('main.dashboard'))

        else:
            logger.warning(f"Authentication failure for: {identity}")
            flash("Invalid credentials, try again.", "warning")
            logger.debug("Login function exited with authentication failure in routes.py")
            return redirect(url_for('main.login'))

    logger.debug("Login function exited from GET request in routes.py")
    return render_template('login.html')


#-------------------------------
@bp.route('/login/security', methods=['GET', 'POST'])
def login_security():
    logger.debug(f"Login security function entered in routes.py method: {request.method}")
    if request.method == 'POST':
        email = request.form['email']
        nickname = request.form['nickname']
        security_question = request.form['security_question']
        security_answer = request.form['security_answer']

        # Search for user info matching what was given
        user = User.query.filter_by(nickname=nickname, email=email).first()
        logger.debug(f"User found for security question: {user.nickname if user else 'None'}")
        
        # Check security question answer
        if user and user.security_answers[security_questions.index(security_question)].lower() == security_answer.lower():
            login_user(user)
            logger.info(f"Security question authentication success for user: {user.nickname}")
            flash("Welcome back! I reccomend changing your password.", "success")
            logger.debug("Login security function exited with success as user in routes.py")
            return redirect(url_for('main.profile'))
        else:
            logger.warning(f"Security question authentication failure for: {nickname} email: {email}")
            flash("Invalid credentials", "warning")
            logger.debug("Login security function exited with authentication failure in routes.py")
            return redirect(url_for('main.login_security'))

    logger.debug("Login security function exited from GET request in routes.py")
    return render_template('login_security.html', security_questions=security_questions)


# ------------------------------
@bp.route('/logout')
@login_required
def logout():
    logger.debug("Logout function entered in routes.py")
    logger.info(f"User logged out: {current_user.nickname}")
    logout_user()
    flash("You have been logged out.", "info")
    logger.debug("Logout function exited in routes.py")

    return redirect(url_for('main.login'))


#-------------------------------
@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    logger.debug(f"Profile function entered in routes.py with method: {request.method}")

    if request.method == 'POST':
        email = request.form['email']
        nickname = request.form['nickname']
        new_pw = request.form['new_password']
        confirm_pw = request.form['confirm_password']

        # Check for email or nickname conflicts
        if email != current_user.email:
            if User.query.filter(User.email == email, User.id != current_user.id).first():
                logger.warning("Profile update failed: Email already taken")
                flash("Email already taken!", "warning")
                return redirect(url_for('main.profile'))

        if nickname != current_user.nickname:
            if User.query.filter(User.nickname == nickname, User.id != current_user.id).first():
                logger.warning(f"Profile update failed: Nickname \"{nickname}\" already taken")
                flash("Nickname already taken!", "warning")
                return redirect(url_for('main.profile'))
            
        # Check if user wants to change password
        if new_pw and confirm_pw:
            if new_pw == confirm_pw:
                current_user.password_hash = generate_password_hash(new_pw)
                logger.info(f"Password updated for user: {current_user.nickname}")
            else:
                flash("Passwords do not match!", "danger")
                return redirect(url_for('main.profile'))
        elif new_pw and not confirm_pw:
            logger.debug("No confirm password provided")
            flash("Please confirm your new password!", "warning")
            return redirect(url_for('main.profile'))

        # Update user info
        current_user.email = email
        current_user.nickname = nickname
        db.session.commit()
        logger.info(f"Profile updated for user: {current_user.nickname}")
        flash("Profile updated successfully!", "success")
        logger.debug("Profile function exited with success in routes.py")
        return redirect(url_for('main.profile'))
    
    # GET request handling
    userInfo = {'email': current_user.email, 'nickname': current_user.nickname}
    return render_template('profile.html', userInfo=userInfo)

#------------------------------
# Read files
def get_file_content(file_path):
    logger.debug(f"get_file_content function entered in routes.py for file: {file_path}")
    try:
        with open(file_path, 'r') as f:
            logger.debug(f"Successfully opened and read file: {file_path}")
            return f.read()
    except FileNotFoundError:
        logger.warning(f"File not found: {file_path}")
        return "File not found."
    except IOError as e:
        logger.warning(f"Error reading file: {e}")
        return "Error reading file."


logLevel = logging.DEBUG
# ------------------------------
# Used to change the log level at runtime from the logging info page
@bp.route('/logging-info', methods=['GET', 'POST'])
@login_required
def logging_info():
    logger.debug(f"logging_info function entered in routes.py method: {request.method}")
    # Get the handler and check if its found
    file_handler = current_app.config.get('FILE_HANDLER')

    if not file_handler:

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='images/logo.png') }}" type="image/png">
    <title>Finance tracker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown-light.min.css">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="{{ url_for('main.dashboard') }}">Finance Tracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.expenses') }}">Expenses</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.incomes') }}">Incomes</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.login') }}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.register') }}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Flash Messages -->
    <div class="container mt-3">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>

    <!-- Content Block -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <!-- Welcome Section -->
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <h1 class="display-4 text-primary">Welcome to your NBA sports betting model!</h1>
            <p class="lead">Your go-to platform for predicting nba game outcomes</p>
        </div>
    </div>

    <!-- About Project Section -->
    <div class="row justify-content-center mt-4">
        <div class="col-md-8 text-center">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h3 class="card-title">About the App</h3>
                    <p class="card-text">Explain here</p>
                    <p>Built with Flask and Bootstrap. Flask-Login for authentication, and ... for ... .</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Action Buttons Section -->
    <div class="row justify-content-center mt-4">
        <div class="col-md-4">
            <a href="{{ url_for('main.login') }}" class="btn btn-primary btn-lg w-100 mb-3">Login</a>
        </div>
        <div class="col-md-4">
            <a href="{{ url_for('main.register') }}" class="btn btn-success btn-lg w-100 mb-3">Register</a>
        </div>
    </div>
    
    <!-- Documentation Section -->
        <div class="row justify-content-center mt-4">
            <div class="col-md-8">
                <div class="card shadow-sm p-3">
                    <h3>Documentation</h3>
                    <div>
                        {{ content }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/logging_info.html
{% extends 'base.html' %}
{% block content %}
<div class="card shadow-sm mt-4">
    <div class="card-body">
        <h2>Logging Info</h2>
        <div class="mb-3 d-flex justify-content-between">
            <p>Logging information.</p>
            <button id="scrollDnBtn" class="btn btn-outline-primary" onclick="scrollToSpot('bottom')">Go to Bottom</button>
        </div>
        <div class="mt-4">
            <h5>Current Log Level: {{ current_level }}</h5>
            <p>You can change it to:</p>
            <div class="mb-3" aria-label="Log Level Buttons">

                <!-- Form for DEBUG -->
                <form method="POST" action="{{ url_for('main.logging_info', level='DEBUG') }}" style="display: inline;">
                    <button type="submit" class="btn btn-outline-primary">DEBUG</button>
                </form>

                <!-- Form for INFO -->
                <form method="POST" action="{{ url_for('main.logging_info', level='INFO') }}" style="display: inline;">
                    <button type="submit" class="btn btn-outline-success">INFO</button>
                </form>

                <!-- Form for WARNING -->
                <form method="POST" action="{{ url_for('main.logging_info', level='WARNING') }}" style="display: inline;">
                    <button type="submit" class="btn btn-outline-danger">WARNING</button>
                </form>

                <!-- Form for ERROR -->
                <!-- <form method="POST" action="{{ url_for('main.logging_info', level='ERROR') }}" style="display: inline;">
                    <button type="submit" class="btn btn-outline-secondary">ERROR</button>
                </form> -->

            </div>
            <p></p>
            <p>Your log file:</p>
            <pre>{{ log_file }}</pre>
            <div class="mb-3 d-flex justify-content-end">
                <button id="scrollUpBtn" class="btn btn-outline-primary" onclick="scrollToSpot('top')">Go to Top</button>
            </div>
    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% block content %}
<h2>Login</h2>
<form method="POST" class="mt-3">
    <div class="mb-3">
        <label>Email or Nickname</label>
        <input type="text" name="identity" class="form-control" autocomplete="new-password" required>
    </div>
    <div class="mb-3">
        <label>Password</label>
        <input type="password" name="password" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-success">Login</button>
</form>
<div class="mt-3 d-flex justify-content-end">
    <a class="btn btn-outline-warning w-25" href="{{ url_for('main.login_security') }}">Forgot Password</a>
</div>
{% endblock %}

app/templates/login_security.html
{% extends 'base.html' %}
{% block content %}
<h2>Login</h2>
<form method="POST" class="mt-3">
    <div class="mb-3">
        <label>Email</label>
        <input type="text" name="email" class="form-control" autocomplete="new-password" required>
    </div>
    <div class="mb-3">
        <label>Nickname</label>
        <input type="text" name="nickname" class="form-control" autocomplete="new-password" required>
    </div>
    <!-- Choice of security question to log in with -->
    <div class="mb-3">
        <label>Security Question</label>
        <p>Choose one of the following security questions:</p>
        <select name="security_question" class="form-control" required>
            {% for question in security_questions %}
            <option value="{{ question }}">{{ question }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label>Security Answer</label>
        <input type="text" name="security_answer" class="form-control" autocomplete="new-password" required>
    </div>
    <button type="submit" class="btn btn-success">Login</button>
</form>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="card shadow-sm mt-4">
    <div class="card-body">
        <h2>Your Profile</h2>
        <p>Manage your profile information.</p>
        <form method="POST" class="mt-3">
            <!-- User info -->
            <div class="mb-3">
                <div class="mb-3">
                    <label>Nickname</label>
                    <input type="text" name="nickname" class="form-control w-50" value="{{ userInfo.nickname }}" required>
                </div>
                <div class="mb-3">
                    <label>Email</label>
                    <input type="email" name="email" class="form-control w-50" value="{{ userInfo.email }}" required>
                </div>
            </div>
            <!-- Button to toggle the hidden section -->
            <button class="btn btn-secondary mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#passwordSection">
                Change Password
            </button>
            <!-- Change password section -->
            <div class="collapse" id="passwordSection">
                <div class="card card-body mb-3">
                    <div class="mb-3">
                        <label class="form-label">New Password</label>
                        <input type="password" id="new_password" name="new_password" class="form-control w-50">
                    </div>
                        <div class="mb-3">
                        <label class="form-label">Confirm New Password</label>
                        <input type="password" id="confirm_password" name="confirm_password" class="form-control w-50">
                        <!-- Check if passwords match at runtime -->
                        <div id="passwordError" class="invalid-feedback">
                            Passwords do not match!
                        </div>
                    </div>
                </div>
            </div>
            <div class="mb-3 d-flex justify-content-end">
                <button type="submit" id="submitBtn" class="btn btn-success">Update Profile</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% block content %}
<h2>Register</h2>
<form method="POST" class="mt-3">
    <!-- All parts must be filled out -->
    <div class="mb-3">
        <label>Email</label>
        <input type="email" name="email" class="form-control" autocomplete="new-password" required>
    </div>
    <div class="mb-3">
        <label>Nickname</label>
        <input type="text" name="nickname" class="form-control" autocomplete="new-password" required>
    </div>
    <div class="mb-3">
        <label>Password</label>
        <input type="password" name="password" class="form-control" required>
    </div>
    <div class="mb-3">
        <h3>Security Questions</h3>
        <p>{{ security_questions[0] }}</p>
        <input type="text" name="answer1" class="form-control" autocomplete="new-password" required>
        <p>{{ security_questions[1] }}</p>
        <input type="text" name="answer2" class="form-control" autocomplete="new-password" required>
        <p>{{ security_questions[2] }}</p>
        <input type="text" name="answer3" class="form-control" autocomplete="new-password" required>
    </div>
    
    <button type="submit" class="btn btn-primary">Register</button>
</form>
{% endblock %}